language: node_js
node_js:
  - 7.8.0
script: npm run build --production

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  local_dir: build
  api_key: $GITHUB_TOKEN
  file: "FILE TO UPLOAD"
  on:
    tags: true